<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="1" total="2" passed="0">
  <reporter-output>
    <line>
      <![CDATA[--> username entered]]>
    </line>
    <line>
      <![CDATA[--> password entered]]>
    </line>
    <line>
      <![CDATA[--> Login button clicked]]>
    </line>
    <line>
      <![CDATA[--> Customer Selected]]>
    </line>
    <line>
      <![CDATA[--> Custome verified before deletion]]>
    </line>
    <line>
      <![CDATA[--> Customer Deleted]]>
    </line>
    <line>
      <![CDATA[-------------------> deleteCustomer is Failed]]>
    </line>
    <line>
      <![CDATA[------------------->Failure Screenshot has been Taken]]>
    </line>
    <line>
      <![CDATA[--> Browser closed]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="32849" started-at="2018-11-18T19:29:14Z" finished-at="2018-11-18T19:29:47Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="32849" started-at="2018-11-18T19:29:14Z" finished-at="2018-11-18T19:29:47Z">
      <class name="com.actitime.testScripts.TasksTestCase">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.actitime.testScripts.TasksTestCase@52f759d7]" name="setUp" is-config="true" duration-ms="26686" started-at="2018-11-18T19:29:14Z" finished-at="2018-11-18T19:29:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="deleteCustomer()[pri:4, instance:com.actitime.testScripts.TasksTestCase@52f759d7]" name="deleteCustomer" duration-ms="4705" started-at="2018-11-18T19:29:41Z" finished-at="2018-11-18T19:29:46Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertFalse(Assert.java:65)
at org.testng.Assert.assertFalse(Assert.java:75)
at com.actitime.pageObjects.ActiveProjNCustPage.verifyCustomerDeletion(ActiveProjNCustPage.java:55)
at com.actitime.testScripts.TasksTestCase.deleteCustomer(TasksTestCase.java:61)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[--> username entered]]>
            </line>
            <line>
              <![CDATA[--> password entered]]>
            </line>
            <line>
              <![CDATA[--> Login button clicked]]>
            </line>
            <line>
              <![CDATA[--> Customer Selected]]>
            </line>
            <line>
              <![CDATA[--> Custome verified before deletion]]>
            </line>
            <line>
              <![CDATA[--> Customer Deleted]]>
            </line>
          </reporter-output>
        </test-method> <!-- deleteCustomer -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.actitime.testScripts.TasksTestCase@52f759d7]" name="tearDown" is-config="true" duration-ms="1431" started-at="2018-11-18T19:29:46Z" finished-at="2018-11-18T19:29:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=deleteCustomer status=FAILURE method=TasksTestCase.deleteCustomer()[pri:4, instance:com.actitime.testScripts.TasksTestCase@52f759d7] output=--> username entered]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[-------------------> deleteCustomer is Failed]]>
            </line>
            <line>
              <![CDATA[------------------->Failure Screenshot has been Taken]]>
            </line>
            <line>
              <![CDATA[--> Browser closed]]>
            </line>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.actitime.testScripts.TasksTestCase -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
